name: Check Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1" # choose your PHP version here

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Add .env File
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  # steps:
  # - name: deploy using ssh
  #   uses: appleboy/ssh-action@v1.0.3
  #   with:
  #     host: ${{ secrets.HOST }}
  #     username: ${{ secrets.USERNAME }}
  #     password: ${{ secrets.PASSWORD }}
  #     port: ${{ secrets.PORT }}
  #     script: whoami
